- name: Install DHCP
  yum:
    name: dhcp-server
    state: present

- name: Install DHCP Config File
  template:
    src: dhcpd.conf
    dest: /etc/dhcp/dhcpd.conf 


# TODO: Generate from hunter list? How would we enforce IPs for nodes?"
- name: Create DHCP Hosts Files
  file:
    path: /etc/dhcp/dhcpd.hosts
    state: touch

- name: Run DHCP
  service:
    name: dhcpd
    state: restarted
    enabled: yes

